file="../../../analysis_n0235_run/LFV.root"
samples="HWW, Ztt_ZttEW, Zll_ZEW, Top, Diboson, Wjets, Signal, data_all"
regions="Baseline, VBF, Optimized"
#regions="Baseline"
channels="emu, mue"
#channels="emu"
echo -e "\nRunning make_yield_table with inputs:"
echo -e "\tFile:     $file"
echo -e "\tSamples:  $samples"
echo -e "\tRegions:  $regions"
echo -e "\tChannels: $channels"
python make_yield_table.py "$file" "$samples" -r "$regions" -c "$channels"
