file="../../../analysis_n0235_run/LFV.root"
samples="Htt, HWW, Ztt_ZttEW, Zll_ZEW, Top, Diboson, Wjets, Signal, data_all"
#regions="VBF, Optimized, Baseline"
regions="Optimized"
channels="emu, mue"
#channels="emu"
#blinded_regions="VBF, Optimized"
blinded_regions=""
echo -e "\nRunning make_yield_table with inputs:"
echo -e "\tFile:     $file"
echo -e "\tSamples:  $samples"
echo -e "\tRegions:  $regions"
echo -e "\tBlinded Regions:  $blinded_regions"
echo -e "\tChannels: $channels"
python make_yield_table.py "$file" "$samples" -r "$regions" -c "$channels" -b "$blinded_regions"
